name: Lighthouse Rating

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    lighthouse:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        env:
            HUGO_VERSION: 0.128.0
        steps:
            - name: Install Hugo CLI
              run: |
                  wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
                  && sudo dpkg -i ${{ runner.temp }}/hugo.deb
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Build Hugo Site
              run: |
                  git clone https://github.com/medialesson/hugo-theme-event.git themes/event

                  touch hugo.yaml
                  echo "theme: event" >> hugo.yaml
                  echo "languages:" >> hugo.yaml
                  echo "  en:" >> hugo.yaml
                  echo "    disabled: false" >> hugo.yaml
                  echo "  de:" >> hugo.yaml
                  echo "    disabled: false" >> hugo.yaml
                  echo "params:" >> hugo.yaml
                  echo "  themes:" >> hugo.yaml
                  echo "    event:" >> hugo.yaml
                  echo "      sessionizeId: test" >> hugo.yaml

                  hugo --minify
            - name: Run Lighthouse CI
              run: npx @lhci/cli autorun
